In [2]:
import numpy as np
import pandas as pd

In [3]:
bios = pd.read_csv("./clean-data/bios.csv")

In [4]:
import sys
print(sys.getsizeof(bios),"Bytes")

139391625 Bytes

In [5]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### What should we cleanup?

- [X] Get rid of bullet points in used name columns
- [X] split height / weight
- [X] parse out date, place from `born` and `died` columns
- [ ] parse out city, region and country from `born` column
- [ ] Get rid of unnecessary columns

In [6]:
df = bios.copy()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [8]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
len(df[df['Used name'].str.contains("•")])

145500

In [10]:
df["name"] = df["Used name"].str.replace("•", " ")

In [11]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

#### **Task 1 completed bullets removed**

In [12]:
df.iloc[1,8].split(" / ")[0]

'183 cm'

In [13]:
# height handling extracts all heights befor " / " and also replaces cm with [space] and
# changes the Dtype of column from object to numeric
df["height_cm"] = df["Measurements"].str.split(" / ").str[0].str.replace(" cm", "") \
   .apply(pd.to_numeric, errors='coerce')
# Weight handling this is different I stucked little bit here like there was only weight values in some rows
# so i am getting NaN in weight cloumn for that problem I took litte help from AI
df["weight_kg"] = df["Measurements"].apply(lambda x: x.split(" / ")[1] if isinstance(x, str) and " / " in x else x) \
    .str.replace(" kg", "").apply(pd.to_numeric, errors='coerce')

In [14]:
# Check to make sure all the values contains ' / ' or not
df[~df["Measurements"].str.contains("/", na=False) & df["Measurements"].notna()].head(10)

# remove all cm and kg - removed

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178.0,NaN
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191.0,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,NaN,120.0
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161.0,NaN
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161.0,NaN
255,Competed in Olympic Games,Male,Denny Kwan•Kantono,Denny•Kantono,"12 January 1970 in Samarinda, Kalimantan Timur...",NaN,Indonesia,256,182 cm,"PB Djarum, Kudus (INA)",NaN,NaN,NaN,NaN,NaN,NaN,Denny Kantono,182.0,NaN
289,Competed in Olympic Games,Male,Ángel•Bello,Ángel•Bello,"9 January 1951 in Vigo, Pontevedra (ESP)",13 June 2013,Argentina,290,65 kg,"Tiro Federal de Lomas de Zamora, Lomas de Zamo...",NaN,NaN,NaN,NaN,NaN,NaN,Ángel Bello,NaN,65.0
290,Competed in Olympic Games,Male,Claudio A.•Pafundi,Claudio•Pafundi,31 January 1962,NaN,Argentina,291,76 kg,"Tiro Federal General José de San Martín, San M...",NaN,NaN,NaN,NaN,NaN,NaN,Claudio Pafundi,NaN,76.0
305,Competed in Olympic Games,Male,Graeme•Telford,Graeme•Telford,19 March 1942,NaN,Australia,306,185 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Graeme Telford,185.0,NaN
313,Competed in Olympic Games,Male,André•Baeyens,André•Baeyens,"29 September 1946 in Erondegem, Oost-Vlaandere...",NaN,Belgium,314,168 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,André Baeyens,168.0,NaN

In [15]:
# get rid of weight not added to weight_kg
# lambda function is added to check the conditions if there is only weight it will go to
# weight_kg column 
# - done

In [16]:
df.head(20)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Nicolas Chatelain,181.0,70.0
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",NaN,NaN,NaN,NaN,NaN,NaN,Patrick Chila,180.0,73.0
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,Le Magicien,NaN,NaN,NaN,NaN,NaN,Henri Cochet,NaN,NaN
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marcel Cousin,NaN,NaN
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN
10,Competed in Olympic Games,Male,Élie Marie Gabriel•Dor de Lastours,"Élie, Comte•de Lastours","12 August 1874 in Orgeval, Yvelines (FRA)","18 November 1932 in Castres, Tarn (FRA)",France,11,NaN,NaN,NaN,Comte (Count),NaN,NaN,NaN,NaN,"Élie, Comte de Lastours",NaN,NaN
11,Competed in Olympic Games • Competed in Interc...,Male,"Maxime Omer Mathieu ""Max""•Omer-Decugis",Max•Decugis,"24 September 1882 in Paris XVIe, Paris (FRA)","6 September 1978 in Biot, Alpes-Maritimes (FRA)",France,12,NaN,Sporting Club de France,NaN,NaN,NaN,NaN,NaN,NaN,Max Decugis,NaN,NaN
12,Competed in Olympic Games,Male,J.•Defert,J.•Defert,NaN,NaN,France,13,NaN,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,J. Defert,NaN,NaN
13,Competed in Olympic Games,Male,Étienne•Durand,Étienne•Durand,NaN,NaN,France,14,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Étienne Durand,NaN,NaN
14,Competed in Olympic Games,Male,Damien•Éloi,Damien•Éloi,"4 July 1969 in Vire, Calvados (FRA)",NaN,France,15,165 cm / 58 kg,"Caen TTC, Caen (FRA) / SAG Cestas, Cestas (FRA...",NaN,NaN,NaN,NaN,NaN,NaN,Damien Éloi,165.0,58.0
15,Competed in Olympic Games,Male,Marie Joseph Adrien•Fauchier-Magnan,Adrien•Fauchier-Magnan,"19 November 1873 in Paris VIIIe, Paris (FRA)","6 August 1965 in Cannes, Alpes-Maritimes (FRA)",France,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adrien Fauchier-Magnan,NaN,NaN
16,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Forget,Guy•Forget,"4 January 1965 in Casablanca, Casablanca-Setta...",NaN,France,17,189 cm / 79 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Guy Forget,189.0,79.0
17,Competed in Olympic Games,Male,Jean-Philippe•Gatien,Jean-Philippe•Gatien,"16 October 1968 in Alès, Gard (FRA)",NaN,France,18,178 cm / 73 kg,"Levallois SC, Levallois-Perret (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Jean-Philippe Gatien,178.0,73.0
18,Competed in Olympic Games • Competed in Interc...,Male,Marie Claude Maurice•Germot,Maurice•Germot,"15 November 1882 in Vichy, Allier (FRA)","6 August 1958 in Vichy, Allier (FRA)",France,19,NaN,Sporting Club Vichy,NaN,NaN,NaN,NaN,NaN,NaN,Maurice Germot,NaN,NaN
19,Competed in Olympic Games,Male,Henry Maurice André•Gobert,André•Gobert,"30 September 1890 in Paris XVIIe, Paris (FRA)","6 December 1951 in Paris VIIe, Paris (FRA)",France,20,NaN,"Sporting Club d'Houlgate, Houlgate (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Gobert,NaN,NaN

### Task 2 Completed ⬆

----------------------------------------------------------------

In [17]:
df.sort_values('height_cm', ascending=False) # who is tallest athlete?

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
89070,Competed in Olympic Games • Other,Male,Yao•Ming,Yao•Ming,"12 September 1980 in Xuhui District, Shanghai ...",NaN,People's Republic of China,89782,226 cm / 141 kg,"Shanghai Sharks, Shanghai (CHN) / Houston Rock...",NaN,NaN,NaN,NaN,姚•明,Oriental,Yao Ming,226.0,141.0
5781,Competed in Olympic Games,Male,"Thomas Loren ""Tommy""•Burleson",Tommy•Burleson,"24 February 1952 in Crossnore, North Carolina ...",NaN,United States,5804,223 cm / 102 kg,"NC State Wolfpack, Raleigh (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Tommy Burleson,223.0,102.0
6978,Competed in Olympic Games,Male,Arvydas Romas•Sabonis,Arvydas•Sabonis,"19 December 1964 in Kaunas, Kaunas (LTU)",NaN,Lithuania Soviet Union,7013,223 cm / 122 kg,"Žalgiris Kaunas, Kaunas (LTU) / Real Madrid, M...",Sabas,NaN,"Arvidas Romas Sabonis, Арвидас Ромас Сабонис",Lithuania,NaN,NaN,Arvydas Sabonis,223.0,122.0
89075,Competed in Olympic Games,Male,Roberto•Dueñas Hernández,Roberto•Dueñas,"1 November 1975 in Madrid, Madrid (ESP)",NaN,Spain,89787,221 cm / 137 kg,"FC Barcelona, Barcelona (ESP)",NaN,NaN,NaN,NaN,NaN,NaN,Roberto Dueñas,221.0,137.0
120266,Competed in Olympic Games,Male,Zhang•Zhaoxu,Zhang•Zhaoxu,"18 November 1987 in Binzhou, Shandong (CHN)",NaN,People's Republic of China,122147,221 cm / 110 kg,"Shanghai Sharks, Shanghai (CHN)",NaN,NaN,NaN,NaN,张•兆旭,Oriental,Zhang Zhaoxu,221.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,Competed in Olympic Games,Male,Sin•Ye-Chan,Sin•Ye-Chan,13 June 1995,NaN,Republic of Korea,149217,NaN,NaN,NaN,NaN,Shin Ye-Chan,NaN,신•예찬,Oriental,Sin Ye-Chan,NaN,NaN
145491,Competed in Olympic Games,Male,Matthew•Wepke,Matthew•Wepke,5 December 1989,NaN,Jamaica,149218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matthew Wepke,NaN,NaN
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos•García-Ordóñez,"24 April 1927 in La Habana (Havana), Ciudad de...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlos García-Ordóñez,NaN,NaN
145493,Competed in Olympic Games,Female,Landysh Ilsurovna•Falyakhova,Landysh•Falyakhova,"31 August 1998 in Dva Polya Artash, Respublika...",NaN,ROC,149220,NaN,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Ландыш Ильсуровна•Фаляхова,NaN,Landysh Falyakhova,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

### Parse out dates from 'Born' and 'Died' columns

In [18]:
df.iloc[91, 4].split(" in ")[0]

'1876'

In [19]:
# Checking for rows which only contains date but no place without NaN value rows
df[~df["Born"].str.contains("in", na=False) & df["Born"].notna()]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
164,Competed in Olympic Games,Female,Helen•Amankwah,Helen•Amankwah,13 April 1964,NaN,Ghana,165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Helen Amankwah,NaN,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,NaN,120.0
166,Competed in Olympic Games,Female,Patience Abena•Opokua,Patience•Opokua,17 June 1969,NaN,Ghana,167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patience Opokua,NaN,NaN
167,Competed in Olympic Games,Male,Winifred•Addy,Winifred•Addy,17 March 1973,NaN,Ghana,168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winifred Addy,NaN,NaN
169,Competed in Olympic Games,Female,Olga•Tsarmpopoulou,Olga•Tsarmpopoulou,19 June 1968,NaN,Greece,170,170 cm / 58 kg,NaN,NaN,NaN,"Olga Tsarmbopoulou, Olga Tsarbopoulou",NaN,Ολγα•Τσαρμπόπουλος,NaN,Olga Tsarmpopoulou,170.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145483,Competed in Olympic Games,Female,Feng•He,Feng•He,31 March 2004,NaN,People's Republic of China,149210,NaN,NaN,NaN,NaN,NaN,NaN,冯•贺,Oriental,Feng He,NaN,NaN
145486,Non-starter,Male,Dmitry•Karlagachev,Dmitry•Karlagachev,13 October 1998,NaN,ROC,149213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dmitry Karlagachev,NaN,NaN
145489,Competed in Olympic Games,Male,Ye•Jielong,Ye•Jielong,2 March 2000,NaN,People's Republic of China,149216,NaN,NaN,NaN,NaN,NaN,NaN,叶•杰龙,Oriental,Ye Jielong,NaN,NaN
145490,Competed in Olympic Games,Male,Sin•Ye-Chan,Sin•Ye-Chan,13 June 1995,NaN,Republic of Korea,149217,NaN,NaN,NaN,NaN,Shin Ye-Chan,NaN,신•예찬,Oriental,Sin Ye-Chan,NaN,NaN
145491,Competed in Olympic Games,Male,Matthew•Wepke,Matthew•Wepke,5 December 1989,NaN,Jamaica,149218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matthew Wepke,NaN,NaN

In [20]:
# Extracting birhtdate using reg exp
date_pattern = r'(\d+ \w+ \d{4}|\d{4})'
df['born_date'] = df['Born'].str.extract(date_pattern)
df['born_year'] = df['Born'].str.extract(r'(\d{4})')

df['born_date'] = pd.to_datetime(df['born_date'], format="mixed", errors='coerce')
df['born_year'] = pd.to_numeric(df['born_year'], errors='coerce')

df['died_date'] = df['Died'].str.extract(date_pattern)
df['died_date'] = pd.to_datetime(df['died_date'], format="mixed", errors='coerce')

In [21]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1886.0,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,1898-08-13,1898.0,1994-07-17
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1895.0,1978-03-20
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1878.0,1930-07-25

In [22]:
df[~df["Born"].str.match(date_pattern, na=False) & df["Born"].notna()]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
1251,Competed in Olympic Games,Male,Eduardo•Cornejo Díaz,Eduardo•Cornejo,(c. 1929),"23 November 1998 in Santiago, Santiago Metropo...",Chile,1258,NaN,NaN,...,NaN,NaN,NaN,NaN,Eduardo Cornejo,NaN,NaN,1929-01-01,1929.0,1998-11-23
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel•Videla,(circa 1920),NaN,Chile,1284,NaN,NaN,...,NaN,NaN,NaN,NaN,Manuel Videla,NaN,NaN,1920-01-01,1920.0,NaT
1794,Competed in Olympic Games,Male,Luis•Castillo Sánchez,Luis•Castillo,"in Guayaquil, Guayas (ECU)",NaN,Ecuador,1801,NaN,NaN,...,NaN,NaN,NaN,NaN,Luis Castillo,NaN,NaN,NaT,NaN,NaT
1800,Competed in Olympic Games,Male,Lincoln•Salcedo Reina,Lincoln•Salcedo,"in Guayaquil, Guayas (ECU)",NaN,Ecuador,1807,NaN,NaN,...,NaN,NaN,NaN,NaN,Lincoln Salcedo,NaN,NaN,NaT,NaN,NaT
1805,Competed in Olympic Games,Male,Gharib Ibrahim•Afifi,Gharib•Afifi,"in Al-Qahira (Cairo), Al-Qahira (EGY)",(In the 1990s),Egypt,1812,NaN,"El-Olympi, Al-Iskanderiya (EGY)",...,NaN,NaN,غريب ابراهيم•عفيفي,NaN,Gharib Afifi,NaN,NaN,NaT,NaN,1990-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86829,Competed in Olympic Games,Male,Charles•Jenny,Charles•Jenny,"April 1897 in Basel, Basel-Stadt (SUI)",NaN,Switzerland,87523,178 cm,NaN,...,NaN,NaN,NaN,NaN,Charles Jenny,178.0,NaN,1897-01-01,1897.0,NaT
100003,Competed in Olympic Games,Male,Gora Chand•Seal,Gora•Seal,January 1923,"23 September 2017 in Kolkata (Calcutta), West ...",India,100829,NaN,"Central Swimming Club, Kolkata (IND)",...,NaN,NaN,NaN,NaN,Gora Seal,NaN,NaN,1923-01-01,1923.0,2017-09-23
101533,Competed in Olympic Games,Male,David Hey•Bratton,David•Bratton,"October 1869 in New York, New York (USA)","3 December 1904 in Chicago, Illinois (USA)",United States,102423,NaN,"NYAC, New York (USA)",...,NaN,NaN,NaN,NaN,David Bratton,NaN,NaN,1869-01-01,1869.0,1904-12-03
101534,Competed in Olympic Games,Male,David A.•Hesser,David•Hesser,"January 1884 in ?, New York (USA)","13 February 1908 in Manhattan, New York, New Y...",United States,102424,NaN,"NYAC, New York (USA)",...,NaN,NaN,NaN,NaN,David Hesser,NaN,NaN,1884-01-01,1884.0,1908-02-13
116330,Competed in Olympic Games,Female,Cha•Yong-Hwa,Cha•Yong-Hwa,"in Pyeongyang, Pyeongyang (PRK)",NaN,Democratic People's Republic of Korea,117719,145 cm / 39 kg,Pyongyang Sports Club,...,NaN,NaN,NaN,Oriental,Cha Yong-Hwa,145.0,39.0,NaT,NaN,NaT

### Task 3 completed ⬆

-------------------------------------

Get city, region and country from 'Born' Coulmn

In [23]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1886.0,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,1898-08-13,1898.0,1994-07-17
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1895.0,1978-03-20
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1878.0,1930-07-25

In [24]:
location_pattern = r'in ([\w\s-]+),\s+([\w\s-]+)\s+\((\w+)\)'

df[['born_city', 'born_region', 'born_country']] = df["Born"].str.extract(location_pattern)

In [25]:
df.head(60)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1886.0,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,1898-08-13,1898.0,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1895.0,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,1878-04-17,1878.0,1930-07-25,Wandsworth,England,GBR
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",...,NaN,Nicolas Chatelain,181.0,70.0,1970-01-13,1970.0,NaT,Amiens,Somme,FRA
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",...,NaN,Patrick Chila,180.0,73.0,1969-11-27,1969.0,NaT,Ris-Orangis,Essonne,FRA
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,...,NaN,Henri Cochet,NaN,NaN,1901-12-14,1901.0,1987-04-02,Villeurbanne,Rhône,FRA
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,...,NaN,Marcel Cousin,NaN,NaN,1896-08-04,1896.0,1986-08-01,Nîmes,Gard,FRA
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,...,NaN,Guy de la Chapelle,NaN,NaN,1868-07-16,1868.0,1923-08-27,Farges-Allichamps,Cher,FRA
10,Competed in Olympic Games,Male,Élie Marie Gabriel•Dor de Lastours,"Élie, Comte•de Lastours","12 August 1874 in Orgeval, Yvelines (FRA)","18 November 1932 in Castres, Tarn (FRA)",France,11,NaN,NaN,...,NaN,"Élie, Comte de Lastours",NaN,NaN,1874-08-12,1874.0,1932-11-18,Orgeval,Yvelines,FRA
11,Competed in Olympic Games • Competed in Interc...,Male,"Maxime Omer Mathieu ""Max""•Omer-Decugis",Max•Decugis,"24 September 1882 in Paris XVIe, Paris (FRA)","6 September 1978 in Biot, Alpes-Maritimes (FRA)",France,12,NaN,Sporting Club de France,...,NaN,Max Decugis,NaN,NaN,1882-09-24,1882.0,1978-09-06,Paris XVIe,Paris,FRA
12,Competed in Olympic Games,Male,J.•Defert,J.•Defert,NaN,NaN,France,13,NaN,"Racing Club de France, Paris (FRA)",...,NaN,J. Defert,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
13,Competed in Olympic Games,Male,Étienne•Durand,Étienne•Durand,NaN,NaN,France,14,NaN,"TCP, Paris (FRA)",...,NaN,Étienne Durand,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
14,Competed in Olympic Games,Male,Damien•Éloi,Damien•Éloi,"4 July 1969 in Vire, Calvados (FRA)",NaN,France,15,165 cm / 58 kg,"Caen TTC, Caen (FRA) / SAG Cestas, Cestas (FRA...",...,NaN,Damien Éloi,165.0,58.0,1969-07-04,1969.0,NaT,Vire,Calvados,FRA
15,Competed in Olympic Games,Male,Marie Joseph Adrien•Fauchier-Magnan,Adrien•Fauchier-Magnan,"19 November 1873 in Paris VIIIe, Paris (FRA)","6 August 1965 in Cannes, Alpes-Maritimes (FRA)",France,16,NaN,NaN,...,NaN,Adrien Fauchier-Magnan,NaN,NaN,1873-11-19,1873.0,1965-08-06,Paris VIIIe,Paris,FRA
16,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Forget,Guy•Forget,"4 January 1965 in Casablanca, Casablanca-Setta...",NaN,France,17,189 cm / 79 kg,"Racing Club de France, Paris (FRA)",...,NaN,Guy Forget,189.0,79.0,1965-01-04,1965.0,NaT,Casablanca,Casablanca-Settat,MAR
17,Competed in Olympic Games,Male,Jean-Philippe•Gatien,Jean-Philippe•Gatien,"16 October 1968 in Alès, Gard (FRA)",NaN,France,18,178 cm / 73 kg,"Levallois SC, Levallois-Perret (FRA)",...,NaN,Jean-Philippe Gatien,178.0,73.0,1968-10-16,1968.0,NaT,Alès,Gard,FRA
18,Competed in Olympic Games • Competed in Interc...,Male,Marie Claude Maurice•Germot,Maurice•Germot,"15 November 1882 in Vichy, Allier (FRA)","6 August 1958 in Vichy, Allier (FRA)",France,19,NaN,Sporting Club Vichy,...,NaN,Maurice Germot,NaN,NaN,1882-11-15,1882.0,1958-08-06,Vichy,Allier,FRA
19,Competed in Olympic Games,Male,Henry Maurice André•Gobert,André•Gobert,"30 September 1890 in Paris XVIIe, Paris (FRA)","6 December 1951 in Paris VIIe, Paris (FRA)",France,20,NaN,"Sporting Club d'Houlgate, Houlgate (FRA)",...,NaN,André Gobert,NaN,NaN,1890-09-30,1890.0,1951-12-06,Paris XVIIe,Paris,FRA
20,Competed in Olympic Games,Male,Pierre Michel•Hirsch,Pierre•Hirsch,"8 November 1900 in Paris Ie, Paris (FRA)","19 April 1942 in Oświęcim, Małopolskie (POL)",France,21,NaN,"Sporting club de Paris, Paris (FRA)",...,NaN,Pierre Hirsch,NaN,NaN,1900-11-08,1900.0,1942-04-19,Paris Ie,Paris,FRA
21,Competed in Olympic Games,Male,Jean René•Lacoste,René•Lacoste,"2 July 1904 in Paris Xe, Paris (FRA)","12 October 1996 in Saint-Jean-de-Luz, Pyrénées...",France,22,NaN,NaN,...,NaN,René Lacoste,NaN,NaN,1904-07-02,1904.0,1996-10-12,Paris Xe,Paris,FRA
22,Competed in Olympic Games • Non-starter,Male,Daniel Édouard•Lawton,Daniel•Lawton,"27 November 1881 in Cantenac, Gironde (FRA)","27 March 1979 in Bordeaux, Gironde (FRA)",France,23,NaN,NaN,...,NaN,Daniel Lawton,NaN,NaN,1881-11-27,1881.0,1979-03-27,Cantenac,Gironde,FRA
23,Competed in Olympic Games,Male,Louis Paul•Lebreton,Paul•Lebreton,"19 October 1875 in Paris IIe, Paris (FRA)","31 March 1960 in Paris IXe, Paris (FRA)",France,24,NaN,"TCP, Paris (FRA)",...,NaN,Paul Lebreton,NaN,NaN,1875-10-19,1875.0,1960-03-31,Paris IIe,Paris,FRA
24,Competed in Olympic Games,Male,Paul Émile•Lecaron,Paul•Lecaron,"29 July 1863 in Neuilly-sur-Seine, Hauts-de-Se...","17 September 1940 in Paris XVIe, Paris (FRA)",France,25,NaN,"TCP, Paris (FRA)",...,NaN,Paul Lecaron,NaN,NaN,1863-07-29,1863.0,1940-09-17,Neuilly-sur-Seine,Hauts-de-Seine,FRA
25,Competed in Olympic Games,Male,Henri•Leconte,Henri•Leconte,"4 July 1963 in Lillers, Pas-de-Calais (FRA)",NaN,France,26,184 cm / 78 kg,LTC Nice,...,NaN,Henri Leconte,184.0,78.0,1963-07-04,1963.0,NaT,Lillers,Pas-de-Calais,FRA
26,Competed in Olympic Games,Male,Christophe•Legoût,Christophe•Legoût,"6 August 1973 in Montbéliard, Doubs (FRA)",NaN,France,27,177 cm / 75 kg,"Levallois SC, Levallois-Perret (FRA) / Istres ...",...,NaN,Christophe Legoût,177.0,75.0,1973-08-06,1973.0,NaT,Montbéliard,Doubs,FRA
27,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Lejeune,"Guy, Baron•Lejeune",NaN,NaN,France,28,NaN,NaN,...,NaN,"Guy, Baron Lejeune",NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
28,Competed in Olympic Games,Male,Albert•Lippmann,Albert•Lippmann,NaN,NaN,France,29,NaN,"unattached, (MIX)",...,NaN,Albert Lippmann,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN
29,Competed in Olympic Games,Male,Édouard Marie Marc•Mény de Marangue,Édouard•Mény de Marangue,"30 November 1882 in Paris VIe, Paris (FRA)","23 January 1960 in Beaulieu-sur-Mer, Alpes-Mar...",France,30,NaN,NaN,...,NaN,Édouard Mény de Marangue,NaN,NaN,1882-11-30,1882.0,1960-01-23,Paris VIe,Paris,FRA
30,Competed in Olympic Games,Male,André Adrien Hippolyte•Prévost,André•Prévost,"28 February 1875 in Paris VIIIe, Paris (FRA)","22 November 1951 in Neuilly-sur-Seine, Hauts-d...",France,31,NaN,"Tennis Club de Puteaux, Puteaux (FRA)",...,NaN,André Prévost,NaN,NaN,1875-02-28,1875.0,1951-11-22,Paris VIIIe,Paris,FRA
31,Competed in Olympic Games,Male,Guillaume•Raoux,Guillaume•Raoux,"14 February 1970 in Bagnols-sur-Cèze, Gard (FRA)",NaN,France,32,180 cm / 77 kg,"Racing Club de France, Paris (FRA)",...,NaN,Guillaume Raoux,180.0,77.0,1970-02-14,1970.0,NaT,Bagnols-sur-Cèze,Gard,FRA
32,Competed in Olympic Games,Male,Stéphane•Renault,Stéphane•Renault,"1 March 1968 in Barfleur, Manche (FRA)",NaN,France,33,180 cm / 72 kg,HBC,...,NaN,Stéphane Renault,180.0,72.0,1968-03-01,1968.0,NaT,Barfleur,Manche,FRA
33,Competed in Olympic Games • Non-starter,Male,Jean-Pierre•Samazeuilh,Jean-Pierre•Samazeuilh,"17 January 1891 in Bordeaux, Gironde (FRA)","13 April 1965 in Mérignac, Gironde (FRA)",France,34,NaN,NaN,...,NaN,Jean-Pierre Samazeuilh,NaN,NaN,1891-01-17,1891.0,1965-04-13,Bordeaux,Gironde,FRA
34,Competed in Olympic Games,Male,Fabrice Vetea•Santoro,Fabrice•Santoro,"9 December 1972 in Tahiti, Îles du Vent (FPN)",NaN,France,35,177 cm / 68 kg,NaN,...,NaN,Fabrice Santoro,177.0,68.0,1972-12-09,1972.0,NaT,Tahiti,Îles du Vent,FPN
35,Competed in Olympic Games • Administrator,Male,Étienne•Thobois,Étienne•Thobois,"20 September 1967 in Amiens, Somme (FRA)",NaN,France,36,186 cm / 78 kg,"Lille UC, Lille (FRA)",...,NaN,Étienne Thobois,186.0,78.0,1967-09-20,1967.0,NaT,Amiens,Somme,FRA
36,Competed in Olympic Games,Male,Philippe-Edmond Pierre•Verdé-Delisle,Pierre•Verdé-Delisle,"16 May 1877 in Trie-la-Ville, Oise (FRA)","18 July 1960 in Paris VIIe, Paris (FRA)",France,37,NaN,NaN,...,NaN,Pierre Verdé-Delisle,NaN,NaN,1877-05-16,1877.0,1960-07-18,Trie-la-Ville,Oise,FRA
37,Competed in Olympic Games,Female,Frances Helen•Aitchison (-Leisk),Helen•Aitchison,"6 December 1881 in Sunderland, England (GBR)","26 May 1947 in Aylesbury, England (GBR)",Great Britain,38,NaN,NaN,...,NaN,Helen Aitchison,NaN,NaN,1881-12-06,1881.0,1947-05-26,Sunderland,England,GBR
38,Competed in Olympic Games,Female,Winifred Geraldine•Beamish (Ramsey-),Geraldine•Beamish,"23 June 1883 in Forest Gate, England (GBR)","10 May 1972 in St. Pancras, England (GBR)",Great Britain,39,NaN,"Queen's Club, London (GBR)",...,NaN,Geraldine Beamish,NaN,NaN,1883-06-23,1883.0,1972-05-10,Forest Gate,England,GBR
39,Competed in Olympic Games,Female,Penelope Dora Harvey•Boothby (-Geen),Dora•Boothby,"2 August 1881 in Finchley, England (GBR)","22 February 1970 in Hammersmith, England (GBR)",Great Britain,40,NaN,NaN,...,NaN,Dora Boothby,NaN,NaN,1881-08-02,1881.0,1970-02-22,Finchley,England,GBR
40,Competed in Olympic Games,Female,Julie Jane•Bradbury,Julie•Bradbury,"12 February 1967 in Oxford, England (GBR)",NaN,Great Britain,41,175 cm / 64 kg,NaN,...,NaN,Julie Bradbury,175.0,64.0,1967-02-12,1967.0,NaT,Oxford,England,GBR
41,Competed in Olympic Games,Female,Gillian Margaret•Clark,Gillian•Clark,"2 September 1961 in Baghdad, Baghdad (IRQ)",NaN,Great Britain,42,176 cm / 68 kg,Wimbledon,...,NaN,Gillian Clark,176.0,68.0,1961-09-02,1961.0,NaT,Baghdad,Baghdad,IRQ
42,Competed in Olympic Games,Female,Mildred•Coles (-Davis),Mildred•Coles,"9 April 1876 in Cranbrook, England (GBR)","24 February 1937 in Folkestone, England (GBR)",Great Britain,43,NaN,NaN,...,NaN,Mildred Coles,NaN,NaN,1876-04-09,1876.0,1937-02-24,Cranbrook,England,GBR
43,Competed in Olympic Games,Female,Evelyn Lucy•Colyer (-Munro),Evelyn•Colyer,"16 August 1902 in Wandsworth, England (GBR)","4 November 1930 in Bishnath, Assam (IND)",Great Britain,44,NaN,NaN,...,NaN,Evelyn Colyer,NaN,NaN,1902-08-16,1902.0,1930-11-04,Wandsworth,England,GBR
44,Competed in Olympic Games • Non-starter,Female,Charlotte Reinagle•Cooper (-Sterry),Charlotte•Cooper,"22 September 1870 in Ealing, England (GBR)","10 October 1966 in Helensburgh, Scotland (GBR)",Great Britain,45,NaN,"Chiswick Park Lawn Tennis Club, Chiswick (GBR)",...,NaN,Charlotte Cooper,NaN,NaN,1870-09-22,1870.0,1966-10-10,Ealing,England,GBR
45,Competed in Olympic Games,Female,Phyllis Lindrea•Covell (Howkins-),Phyllis•Covell,"22 May 1895 in Paddington, England (GBR)","28 October 1982 in Heyshott, England (GBR)",Great Britain,46,NaN,NaN,...,NaN,Phyllis Covell,NaN,NaN,1895-05-22,1895.0,1982-10-28,Paddington,England,GBR
46,Competed in Olympic Games,Female,Gladys Shirley•Eastlake-Smith (-Lamplough),Gladys•Eastlake-Smith,"14 August 1883 in Lewisham, England (GBR)","18 September 1941 in Middleham, England (GBR)",Great Britain,47,NaN,NaN,...,NaN,Gladys Eastlake-Smith,NaN,NaN,1883-08-14,1883.0,1941-09-18,Lewisham,England,GBR
47,Competed in Olympic Games,Female,Sara Louise•Gomer (-Palombo),Sara•Gomer,"13 May 1964 in Torquay, England (GBR)",NaN,Great Britain,48,190 cm / 85 kg,Riverside,...,NaN,Sara Gomer,190.0,85.0,1964-05-13,1964.0,NaT,Torquay,England,GBR
48,Competed in Olympic Games,Female,Alison Helen•Gordon (-Broe),Alison•Gordon,"31 December 1962 in Reading, England (GBR)",NaN,Great Britain,49,175 cm / 68 kg,NaN,...,NaN,Alison Gordon,175.0,68.0,1962-12-31,1962.0,NaT,Reading,England,GBR
49,Competed in Olympic Games,Female,Gillian Carol•Gowers,Gillian•Gowers,"9 April 1964 in Horfield, Clifton, England (GBR)",NaN,Great Britain,50,157 cm / 55 kg,Gosling,...,NaN,Gillian Gowers,157.0,55.0,1964-04-09,1964.0,NaT,NaN,NaN,NaN
50,Competed in Olympic Games,Female,Alice Norah Gertrude•Greene,Alice•Greene,"15 October 1879 in Upton, England (GBR)","26 October 1956 in Saint Brélade, Jersey (JER)",Great Britain,51,NaN,NaN,...,NaN,Alice Greene,NaN,NaN,1879-10-15,1879.0,1956-10-26,Upton,England,GBR
51,Competed in Olympic Games,Female,Edith Margaret•Hannam (Boucher-),Edith•Hannam,"28 November 1878 in Bristol, England (GBR)","16 January 1951 in Kensington, England (GBR)",Great Britain,52,NaN,NaN,...,NaN,Edith Hannam,NaN,NaN,1878-11-28,1878.0,1951-01-16,Bristol,England,GBR
52,Competed in Olympic Games,Female,Edith Dorothy•Holman,Dorothy•Holman,"18 July 1883 in Kilburn, England (GBR)","15 June 1968 in Brent, England (GBR)",Great Britain,53,NaN,NaN,...,NaN,Dorothy Holman,NaN,NaN,1883-07-18,1883.0,1968-06-15,Kilburn,England,GBR
53,Competed in Olympic Games,Female,Andrea Mary•Holt,Andrea•Holt,"11 November 1970 in Radcliffe, England (GBR)",NaN,Great Britain,54,168 cm / 64 kg,NFD Grove,...,NaN,Andrea Holt,168.0,64.0,1970-11-11,1970.0,NaT,Radcliffe,England,GBR
54,Competed in Olympic Games,Female,Monique Alicia•Javer (-Dias),Monique•Javer,"22 July 1967 in Burlingame, California (USA)",NaN,Great Britain,55,177 cm / 64 kg,NaN,...,NaN,Monique Javer,177.0,64.0,1967-07-22,1967.0,NaT,Burlingame,California,USA
55,Competed in Olympic Games,Female,Valda•Lake,Valda•Lake,"11 October 1968 in Torquay, England (GBR)",NaN,Great Britain,56,173 cm / 61 kg,NaN,...,NaN,Valda Lake,173.0,61.0,1968-10-11,1968.0,NaT,Torquay,England,GBR
56,Competed in Olympic Games,Female,"Dorothea Katherine ""Dorothy""•Lambert Chambers ...",Dorothy•Lambert Chambers,"3 September 1878 in Ealing, England (GBR)","7 January 1960 in Kensington, England (GBR)",Great Britain,57,NaN,NaN,...,NaN,Dorothy Lambert Chambers,NaN,NaN,1878-09-03,1878.0,1960-01-07,Ealing,England,GBR
57,Competed in Olympic Games,Female,Lisa Jane•Lomas (Bellinger-),Lisa•Lomas,"9 March 1967 in Dunstable, England (GBR)",NaN,Great Britain,58,168 cm / 63 kg,Molndais BTK,...,NaN,Lisa Lomas,168.0,63.0,1967-03-09,1967.0,NaT,Dunstable,England,GBR
58,Competed in Olympic Games,Female,"Kathleen ""Kitty""•McKane (-Godfree)",Kitty•McKane,"7 May 1896 in Bayswater, England (GBR)","19 June 1992 in East Sheen, England (GBR)",Great Britain,59,NaN,NaN,...,NaN,Kitty McKane,NaN,NaN,1896-05-07,1896.0,1992-06-19,Bayswater,England,GBR
59,Competed in Olympic Games,Female,Winifred Margaret•McNair (Slocock-),Winifred•McNair,"9 August 1877 in Donnington, England (GBR)","28 March 1954 in Kensington, England (GBR)",Great Britain,60,NaN,NaN,...,NaN,Winifred McNair,NaN,NaN,1877-08-09,1877.0,1954-03-28,Donnington,England,GBR

### Task 4 completed ⬆

-------------------------------------

 #### Remove Unnecessary columns

In [26]:
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'height_cm', 'weight_kg', 'born_date', 'born_year', 'died_date',
       'born_city', 'born_region', 'born_country'],
      dtype='object')

In [28]:
keep_columns = ['athlete_id', 'name', 'Sex', 'born_date', 'born_city', 'born_region',
                'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date']

In [29]:
df_clean = df[keep_columns]

In [30]:
df_clean.head()

,athlete_id,name,Sex,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,Male,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,Male,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,Male,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,Male,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,Male,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

### Task 5 Completed ⬆

--------------------------

In [31]:
df_clean.to_csv("./clean-data/bios-cleaned.csv", index=False)